import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer/Footer";
import HeaderPage from "./_components/header/Header";
import Sidebar from "./_components/sidebar/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./_components/sidebar/app-sidebar";
import { cookies } from "next/headers";
import Login from "./_components/Login";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let token = false;
  const cookieStore = await cookies();
  const isLogin = cookieStore.get('token');
  if(isLogin) token= true;

  

  //const isLoggedIn = !!token;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      {!token ? (<div><Login /></div>):(<SidebarProvider>
      <div className="flex w-full">
        <AppSidebar />
        <main className="flex-1 p-4 w-full">
          <SidebarTrigger />
          {children}
         
        </main>
      </div>
    </SidebarProvider>)} 
  
      </body>
    </html>
  );
}
